export const ITEM_KEYS = {
	INSPIRIT: "INSPIRIT",
	CONTENT_CREATION_MASTERCLASS: "CONTENT_CREATION_MASTERCLASS",
	PRODUCT_GROWTH_MASTERCLASS: "PRODUCT_GROWTH_MASTERCLASS",
	STARTUP_MASTERCLASS: "STARTUP_MASTERCLASS",
	ACCELERATION_PASS: "ACCELERATION_PASS",
	UNICORN_PASS: "UNICORN_PASS",
};
